apiVersion: v1
kind: VmwareNetwork
metadata:
  name: generic_oam_network
dependencies:
  providers:
  - name: generic_provider_access
spec:
  create_network: true
  name: MEDIA
  switchName: vSwitch1
  portGroupName: MEDIA
  activeNics: ["vmnic6"]
  subnet:
    name: MEDIA
    ipv4Netmask: 255.255.255.128
    ipv4Gateway: 172.29.112.129
    ipv6Gateway: 12::1
    ipv6Prefix: 12
    vlanId: 0
