apiVersion: v1
kind: VmwareNetwork
metadata:
  name: generic_private_network
dependencies:
  providers:
  - name: generic_provider_access
spec:
  create_network: true
  switchName: vSwitch2
  portGroupName: SIG
  activeNics: ["vmnic5"]
  subnet:
    ipv4Netmask: 255.255.255.128
    ipv4Gateway: 172.29.112.1
    ipv6Gateway: 12::1
    ipv6Prefix: 12
    vlanId: 0
